name: SCA

on:
  push:
    branches: ["main", "**"]

permissions:
  contents: read

jobs:
  snyk-scan:
    name: Snyk dependency scan
    runs-on: ubuntu-22.04-2cpu-8ram-75ssd  # replace with ubuntu-latest once migrated to public
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Build Environment
        uses: ./.github/actions/setup

      - name: Run Snyk
        uses: atko-security/devsecops-tooling/.github/actions/sca-scan@main
        with:
          additional-arguments: "--all-projects"
          SNYK_TOKEN: ${{ secrets.CIC_SNYK_TOKEN }}
          SIGNAL_HANDLER_TOKEN: ${{ secrets.SIGNAL_HANDLER_TOKEN }}
